---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Mi
  storageClassName: local-hostpath