---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name local-path-provisioner
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      fullnameOverride: *name
      enabled: true
      strategy: node
      externalProvisioner:
        enabled: true
        image:
          registry: registry.k8s.io/sig-storage/csi-provisioner
          tag: v5.3.0
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1
      externalResizer:
        enabled: false
      externalAttacher:
        enabled: false
      externalSnapshotter:
        enabled: false
    csiDriver:
      name: local-hostpath.cluster.local
      storageCapacity: true
      attachRequired: false
      fsGroupPolicy: File
    storageClasses:
      - name: local-hostpath
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
    driver:
      config:
        driver: local-hostpath
        local-hostpath:
          shareBasePath: &storagePath "/var/lib/local-path-provisioner"
          controllerBasePath: *storagePath
          dirPermissionsMode: "0770"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
    node:
      driver:
        image:
          registry: ghcr.io/democratic-csi/democratic-csi
          tag: v1.9.3
        extraVolumeMounts:
          - name: local-hostpath
            mountPath: *storagePath
            mountPropagation: Bidirectional
      extraVolumes:
        - name: local-hostpath
          hostPath:
            path: *storagePath
            type: DirectoryOrCreate
    csiProxy:
      enabled: true
      image:
        registry: docker.io/democraticcsi/csi-grpc-proxy
        tag: v0.5.6