# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:9E5VTxUes3qO2T/usfTFlvFivTtL7bfI2CB3K8SBBR4=,iv:cClwpaGPu0v9dyeJOHjssN5ZL/fLY0NcK+83VE8wJJ8=,tag:zjdeZ1l3Lj92aayrbe0Xfw==,type:str]
sops:
  age:
    - recipient: age1e249m2qfrzm2t7gfv0lrxzl3tcwnw3t23jx9hcn60px94csa0emqzg2f0y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeFoyd2I0azBJMWQ2a3pV
        WmtyOXhUUUpZYnBIdEFyU1l6MGJ4R3Z0aW1rClhqMkdlNkg0TjVaSmczeFlsRXBy
        S2d6VFNKYkUyV25IWjh0bnJZR2ErVHcKLS0tIGtFRmlHaG02Y2h1aktCWG9zWWk1
        bDIySkp6RCtzeUVoQ1UxenZiTjk3ZTAKGhGRhc7BmVIEmO5CSNyPqlC4GgAVTpyD
        dEZSDU6jlDhVCmmLgTTSEWDMlY8WTtFO/1Gh/NmXNmef6JsfUJnw5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-10T02:03:58Z"
  mac: ENC[AES256_GCM,data:+t07sallaOidJVS19SyAT+0OyfJObTfffy6f/j56W6uhAfesRvjyyevLWFvjYKJ/xbKpm0hu5bzXL7cFCLRvd5mrztClM3i9zudQ+EMGuWw2j+de8dUelfDe45/YrcwW2AUcKSoaET6xIjzwGLrSCYGUEtRA0Bn/D7UHYRuKHC4=,iv:res6Bo1UclwW2yi115X+G4OAKSxNkwCaYMGIISWk2fg=,tag:J08l8BWvC2E+Az3dU/9xQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
