# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:GQ87kBpi+ejeD7lfUtNQIaz25zB51urUu5xpX9yQkL0=,iv:AErPROot4GuPMg0lJiT+8OIwSSmEa7s/TcU+kk/ep8o=,tag:HlIOPMLqcBB9GLQ4iaX+Kw==,type:str]
sops:
  age:
    - recipient: age1e249m2qfrzm2t7gfv0lrxzl3tcwnw3t23jx9hcn60px94csa0emqzg2f0y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT1poUkVjS0thTWlkRTJV
        cFFKOUMvR01LbzFJUkF1Q1g5OVVweXdrdzFNCjFxTzZwM2ltem5Wb3o4ZDdPYjRq
        REpXeFZqNjBUR3VHbW5KeGtka3doSDQKLS0tIDA0MHIyNE12THJGM1dLRjAyakhO
        b1doOHNLYlVsMlo1YVVLMHpUWXNpam8KGB/OTkkRLXSpUnDL8xVBVu8zKMmlkWjW
        +m2oAYFUGiBXWCzlYiwErF7l4GwLC8k05HkGjMjCbCbFSdstcpHsUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-09T07:41:17Z"
  mac: ENC[AES256_GCM,data:d+zIXYvMlQkN8nUIsAD7ivtFE8lYOn87FifO4AT6GAjFIq5bnR3yQMiQYwWVgtvKYkjdpz5PzAb5qqR+KlGaTfMGoV5Haf0l8FQ1cooAq53KERPucs4iMSDraOXjjt2PykwsAIk9IxZfwIDMeWq5DoFQChr/xRA/047JQZs1Dbs=,iv:pwgy1ETBr5L2QP9DuatrHnKiBa93eBFYdjKpnxkM0ng=,tag:UNX3WuRC3ytPv/LKDiTXTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
