# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:e1xjEuL52pIpH8yJEJpGzvqb2AmxtDnvZ2t720s3htz7GvflPqeu0jewrbiKAY/2f6IHMqVk6XnZbA4EyHnZQd/4+mJ+t1ERqZ9EIkSj0VC19AUkZzkfs9CE7ZZ6momfWmhQJaub4k1XdVYysXG3UE6bJgnxzkWO+13BAgDCnxtwBVcGZd+QHT0OvTgcJ0FShyh3tfDVVb68vDVicdefZbH3fUTl5XzpsXixmqkSDQDHrqTa,iv:QcsZBISdXgd+t5rXdYV834F4AW+vliGI6qgMS5c7b2M=,tag:0puVTDH263XVbxGy9vIWZg==,type:str]
sops:
  age:
    - recipient: age1e249m2qfrzm2t7gfv0lrxzl3tcwnw3t23jx9hcn60px94csa0emqzg2f0y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOTBMd3V0M3ZvTVVYVStj
        N2JSVnBvM254N1FCeWdMM3Z4OGJ4VDFjZ0FrCm9CSDVjb3NqMmpVUDRCcGVQeFNR
        UWt4UTdxMDJ4ekhmNTRObmdBam5uSm8KLS0tIDNMdjlwaG1BUTZyYjRCYkFkdkZP
        UWNxL3lwQ3dYY2dZUFg1dFRrcW14N2MK11bFFrhklUt6Hm26nha4n4E+kvU9OG1i
        PTDUcPwbKBtcWFCaYa0R7qouFWyBp4oDHd9iuvFdu6YWXXyUEO0zug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-09T07:45:36Z"
  mac: ENC[AES256_GCM,data:kJBMQEMymLvuVP8PolkF22DAiTTkvWaeQ3+13rjc2JTKgra36u3Alcg2ieNdQXh2n+seva5KNpAWvuJo/OV/Du7J4dYNAIbmvr4oT2rTX9H5tXhHwy48Rs+ELi5a3XWDdSy4a9DuuddkvhhQijXP0tpZpKb8EC9kMGqgJFvwAj4=,iv:ImyGuY7lMHZd5B12iXh2EQ/zIiFDk+2IJtnZqPAIoSQ=,tag:GPj6LOHGKdHIWjpjtAafeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
