# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Wehpnj9rv/7HY7H6g9V0ZGyNHR73sN1uS3miz0C1z4kT7IbjlVv2pg==,iv:uvCesLCGLgjuS1SWUn/BEH+QHOiXd76g09TZqaL9OR8=,tag:p8RlgR+iAxuYzNcz5BceGg==,type:str]
sops:
  age:
    - recipient: age1e249m2qfrzm2t7gfv0lrxzl3tcwnw3t23jx9hcn60px94csa0emqzg2f0y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbTNrbWxqdWgwMkZvQUtW
        dW1tb05WaUdqRHJLaEtUdzRwOTVxQkdIZ1JBCkk1MmxkUE9qNVFZT2hzR2JHai8x
        NHRtWFc5bWh1Q29XNHhjUkVxenBLVUUKLS0tIGswZEI5TG1vTVV4RUVsNDgwSEtK
        U0F5TmJBTDVxZk15TEFVc0NjeWJuMXcKNJWdJVZtlectnPGuhmlFXob1VuuFgluQ
        WOlXjLyZ1mo7E/n/8/pCPNA6qQHMmxxP9mgT2oIOB3j+3M55l9CZwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-09T07:41:17Z"
  mac: ENC[AES256_GCM,data:4o2uDIfJd7P2c5Wl1b92vqKc3pzGJaXH6IjlLqOzjrUZhuFYqmdw+B0Qvm1rYkSPLzi1NuTcn2MqgVJ7gw+HvZ1jdEqmLJDHj9ONMa++NCtxXW0ec4XxBKAiRWQpmRZObD0c/PdPgYMwTJDzmX/ttZUTieMSmA37MixWCfEdHLA=,iv:46q+xgIgNGB/dsqtnBHZJCWcrNVlGUR/nrt5IYPv+pA=,tag:NRQGIRiYmsP3IQ/h/XK08g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
