apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: default
labels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/part-of: home-assistant
  app.kubernetes.io/instance: home-assistant
  app.kubernetes.io/component: config
  app.kubernetes.io/managed-by: fluxcd
  fluxcd.io/automated: "true"
  fluxcd.io/health-checks: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
  storageClassName: local-path